### ISSUE TITLE
Manual Intent - How to launch game with Intent?

### ISSUE THREAD

**Issue by profucius** [moonlight-stream/moonlight-android#668]
I am using Moonlight on an Android TV with a launcher that does not directly support shortcuts, however I am using Tasker and wish to "Send an Intent" to make Moonlight open a specific game immediately.

I used a different launcher and created a shortcut, and tried reversing what the Intent is, but am having no luck so far.

What is the Intent (template?) that I can use to launch games directly?

This is a Tasker template, I've filled out what I _think_ is correct so far, but it's still not working yet:

```
Send Intent [ 
 Action: android.intent.action.VIEW
 Cat: None
 Mime Type: 
 Data: com.limelight.shortcuttrampoline
 Extra:
 Extra: 
 Package:
 Class: 
 Target: Broadcast Activity
]
```
